apiVersion: v1
kind: Service
metadata:
  name: k8s-queue
spec:
  selector:
    app: queue
    release: "1"
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: queue-1
  labels:
    app: queue
    release: "1"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1