apiVersion: v1
kind: Service
metadata:
  name: k8s-web
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
