apiVersion: v1
kind: Service
metadata:
  name: k8s-web
spec:
  selector:
    app: web
    release: "0-5"
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: web-release-0
  labels:
    app: web
    release: "0"
spec:
  containers:
  - name: web
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: web-release-0-5
  labels:
    app: web
    release: "0-5"
spec:
  containers:
  - name: web
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
